### ISSUE TITLE
Simple parallelization

### ISSUE THREAD

**Issue by mdavezac** [OPTIMET/OPTIMET#34]
1. create the matrix A and the vector b on root
2. distribute it to n by m processes
3. solve the linear system of equation
4. gather the results

To achieve this simple implementation, I see the following steps, in no particular order
- [x] create an mpi/scalapack interface (#33)
- [x] simplify the creation of A and b in the solver (#35)
- [x] add blacs_gridmap support so we can run multiple instances together (#36)
- [x] parallelize subroutine for solving the linear equations
- [ ] add xml input (and command-line?) to read scalapack specific information (block size, grid
  size, both optional #41 )
- [x] some heuristic to determine n and m of n by m process-grid, if not given on input
- [x] check/correct how output happens when in parallel
